#PostGres Config
spring.datasource.url=jdbc:postgresql://dpg-d6jhj21aae7s73964o3g-a.singapore-postgres.render.com/moneymanager_09pq
spring.datasource.username=moneymanager_09pq_user
spring.datasource.password=Jlg8Uf4l6XmnxGfzlp7zuFEpaQ9HGsE7